DROP TABLE IF EXISTS STD_SER;
CREATE TABLE STD_SER
(
   STD_ID   VARCHAR(255)   NOT NULL,
   S_TITLE  VARCHAR(255)   NOT NULL
);
ALTER TABLE STD_SER
   ADD CONSTRAINT PK_STDSER PRIMARY KEY (STD_ID, S_TITLE);

ALTER TABLE STD_SER   
   ADD CONSTRAINT FK_STD FOREIGN KEY (STD_ID) REFERENCES STUDENT (STD_ID);

ALTER TABLE STD_SER
   ADD CONSTRAINT FK_SER FOREIGN KEY (S_TITLE) REFERENCES SERVICE (S_TITLE);
   
COMMIT;
